name: On Commit

on:
  # push:
  #   branches: [ master ]
  workflow_dispatch:
env:
  SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
  SLACK_ICON: https://icons.iconarchive.com/icons/martz90/circle/256/android-icon.png
  SLACK_TITLE: Commit status
  SLACK_USERNAME: Emarsys SDK - Flutter
  SLACK_WEBHOOK: ${{ secrets.SLACK_MOBILE_TEAM_CI_CHANNEL_WEBHOOK }}

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup flutter env
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.0.5"
          channel: "stable"
          
      - name: PWRD
        run: pwd
          
      - name: ls
        run: ls -la

      - name: Update dependencies
        run: flutter pub get

      - name: Run Flutter Tests
        run: flutter test

      - name: Run Android unit tests with gradle
        run: (cd flutter-emarsys-sdk/example/android && ./gradlew clean build test)

      - name: Run integration tests on Android
        run: pwd

  ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup flutter env
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.0.5"
          channel: "stable"
          
          
      - name: PWRD
        run: pwd
          
      - name: ls
        run: ls -la

      - name: Update dependencies
        run: flutter pub get

      - name: Remove old directories
        run: rm -rf ~/tmp | rm -rf ~/Library/MobileDevice
        shell: bash

      - name: Install Dependencies
        run: (cd flutter-emarsys-sdk/example/ios && pod install --no-repo-update --verbose)
        shell: bash

      - name: Run Flutter Tests
        run: flutter test

      - name: Run iOS unit tests with gradle
        run: xcodebuild -workspace ~/work/flutter-emarsys-sdk/example/ios/EmarsysSDK.xcworkspace -scheme flutter-plugin-ios-tests -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max' -derivedDataPath ~/tmp test

#      - name: Run integration tests on iOS
#        run: echo todo

  slack:
    needs: [android, ios]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Download file 'FAILURE.TXT' from artifact
        uses: actions/download-artifact@v1
        with:
          name: failure_file

      - name: Read file 'FAILURE.TXT' and set output parameter
        id: set_output
        run: echo "::set-output name=FAILURE::$(<failure_file/FAILURE.TXT)"

      - name: Slack Success
        if: steps.set_output.outputs.FAILURE == 'false'
        uses: megamegax/slack_action@0.2.3
        with:
          channel: "${{env.SLACK_CHANNEL}}"
          message: "Last push build successful! :man-gesturing-ok: :bananadance:"
          user_name: "${{env.SLACK_USERNAME}}"
          job_status: "success"
          user_icon: "${{env.SLACK_ICON}}"
          actions: '[{ "type": "button", "text": "View actions", "url": "https://github.com/emartech/flutter-emarsys-sdk/actions" },{ "type": "button", "text": "View Firebase", "url": "https://console.firebase.google.com/project/ems-mobile-sdk/testlab/histories/" },{ "type": "button", "text": "Install page", "url": "http://ems-mobileteam-artifacts.s3-website-eu-west-1.amazonaws.com/index-ems.html" }]'

      - name: Slack Notification
        if: steps.set_output.outputs.FAILURE == 'true'
        uses: megamegax/slack_action@0.2.3
        with:
          channel: "${{env.SLACK_CHANNEL}}"
          message: "Last push build failed! :man-gesturing-no: :blobcatfearful:"
          user_name: "${{env.SLACK_USERNAME}}"
          job_status: "failure"
          user_icon: "${{env.SLACK_ICON}}"
          actions: '[{ "type": "button", "text": "View actions", "url": "https://github.com/emartech/flutter-emarsys-sdk/actions" },{ "type": "button", "text": "View Firebase", "url": "https://console.firebase.google.com/project/ems-mobile-sdk/testlab/histories/" }]'
