name: On Commit

on:
  # push:
  #   branches: [ master ]
  workflow_dispatch:
env:
  SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
  SLACK_ICON: https://icons.iconarchive.com/icons/martz90/circle/256/android-icon.png
  SLACK_TITLE: Commit status
  SLACK_USERNAME: Emarsys SDK - Flutter
  SLACK_WEBHOOK: ${{ secrets.SLACK_MOBILE_TEAM_CI_CHANNEL_WEBHOOK }}

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup flutter env
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.0.5"
          channel: "stable"
          
      - name: Update dependencies
        run: flutter pub get
        
#       - name: start android emulator
#         run: /Users/runner/Library/Android/sdk/emulator/emulator -list-avds

#       - name: Run Flutter Tests
#         run: flutter test

      - name: Run Android unit tests with gradle
        run: (cd example/android && ./gradlew clean build test -x lint)
        
      - name: Build integrésön tszt
        run: (cd example && flutter build apk) | (cd example/android && ./gradlew app:assembleAndroidTest) |  (cd example/android && ./gradlew app:assembleDebug -Ptarget=integration_test/emarsys_test.dart)
        
#       - name: start android emulator
#         run: /Users/runner/Library/Android/sdk/emulator/emulator -list-avds

#       - name: doctore
#         run: flutter doctor -v

      - name: Run integration tests on iOS
        if: always()
        run: |
          (cd example && flutter drive \
            --driver=test_driver/integration_test.dart \
            --target=integration_test/emarsys_test.dart)

#   ios:
#     runs-on: macos-latest
#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v2

#       - name: Setup flutter env
#         uses: subosito/flutter-action@v1
#         with:
#           flutter-version: "2.0.5"
#           channel: "stable"
        
#       - name: ooepqwefrna simulator
#         run: open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app/
          
#       - name: Update dependencies
#         run: flutter pub get

#       - name: Remove old directories
#         run: rm -rf ~/tmp | rm -rf ~/Library/MobileDevice
#         shell: bash

#       - name: Install Dependencies
#         run: (cd example/ios && pod install --no-repo-update --verbose)
#         shell: bash

#       - name: Run Flutter Tests
#         run: flutter test

#       - name: Run iOS unit tests with gradle
#         run: xcodebuild -workspace ~/work/flutter-emarsys-sdk/flutter-emarsys-sdk/example/ios/Runner.xcworkspace -scheme flutter-plugin-ios-tests -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max' test
        
#       - name: Run integration tests on iOS
#         if: always()
#         run: |
#           (cd example && flutter drive \
#             --driver=test_driver/integration_test.dart \
#             --target=integration_test/emarsys_test.dart)
