name: On Commit

on:
  # push:
  #   branches: [ master ]
  workflow_dispatch:
env:
  SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
  SLACK_ICON: https://icons.iconarchive.com/icons/martz90/circle/256/android-icon.png
  SLACK_TITLE: Commit status
  SLACK_USERNAME: Emarsys SDK - Flutter
  SLACK_WEBHOOK: ${{ secrets.SLACK_MOBILE_TEAM_CI_CHANNEL_WEBHOOK }}

jobs:
#   android:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v2

#       - name: Setup flutter env
#         uses: subosito/flutter-action@v1
#         with:
#           flutter-version: "2.0.5"
#           channel: "stable"
          
#       - name: PWRD
#         run: pwd
          
#       - name: ls
#         run: ls -la

#       - name: Update dependencies
#         run: flutter pub get

#       - name: Run Flutter Tests
#         run: flutter test

# #       - name: Run Android unit tests with gradle
# #         run: (cd example/android && ./gradlew clean build test -x lint)

#       - name: Run integration tests on Android
#         run: pwd

  ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup flutter env
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.0.0"
          channel: "stable"
          
          
      - name: PWRD
        run: pwd
          
      - name: ls
        run: ls -la
        
      - name: Simulator list
        run: xcrun simctl list
        
      - name: find simulator
        run: (cd ../../.. && pod install --no-repo-update --verbose)
        
      - name: find simulator
        run: (cd ../.. && pod install --no-repo-update --verbose)
        
      - name: find simulator
        run: (cd .. && pod install --no-repo-update --verbose)
        
      - name: ooepqwefrna simulator
        run: open /Applications/Xcode.app/Contents/Developer/Applications/iOS\ Simulator.app/
          


      - name: Update dependencies
        run: flutter pub get

      - name: Remove old directories
        run: rm -rf ~/tmp | rm -rf ~/Library/MobileDevice
        shell: bash

      - name: Install Dependencies
        run: (cd example/ios && pod install --no-repo-update --verbose)
        shell: bash

      - name: Run Flutter Tests
        run: flutter test

      - name: Run iOS unit tests with gradle
        run: xcodebuild -workspace ~/work/flutter-emarsys-sdk/flutter-emarsys-sdk/example/ios/Runner.xcworkspace -scheme flutter-plugin-ios-tests -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max' test

      - name: doctore
        run: flutter doctor -v
        
        
      - name: open simulator
        run: /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app/Contents/MacOS/Simulator -CurrentDeviceUDID 31065D64-94BA-4F32-9AA7-5139ACF8C454

          
      - name: Run integration tests on iOS
        if: always()
        run: |
          flutter drive \
            --driver=example/test_driver/integration_test.dart \
            --target=example/integration_test/emarsys_test.dart -d 31065D64-94BA-4F32-9AA7-5139ACF8C454
